### ISSUE TITLE
How to override the 'proxied' setting?

### ISSUE THREAD

**Issue by begna112** [containeroo/SyncFlaer#102]
I have some dockers which are extremely sensitive to cloudflare proxying. Disabling the proxy for that cname fixes consistently, but then syncflaer reverts it. 

I've tried setting up an `additionalRecords` for it but I think it's skipping it because it's got a record from Traefik:

```
time="2022-02-15T07:16:42Z" level=info msg="Updated: name: wiki.example.com, type: CNAME, content: weeb.house, proxied: true, ttl: 1"
time="2022-02-15T07:17:43Z" level=warning msg="DNS record wiki.example.com is already defined in a Traefik route. Skipping..."
```

How can I override the traefik information with docker/compose? I think this ability exists with the kubernetes config?

**Comment by rxbn** [comment]
Hey @begna112 

Thanks for opening an issue!

Currently, the only way to define the `proxied` setting for Traefik hosts is by using the `cloudflare.defaults.proxied` key in the configuration file. This, however, means that all your DNS records will not be proxied. Overriding a single host is not yet possible, but I think we may come up with an elegant solution.

In the meantime, you could use our `Ingress` integration and set the following annotation on the `wiki.example.com` ingress:

`syncflaer.containeroo.ch/proxied="false"`

Is this a viable solution for you until we figure out how to define overrides?

-- rxbn

**Comment by gi8lino** [comment]
Hey @begna112 
See here [how](https://github.com/containeroo/SyncFlaer#kubernetes-ingress-support) how to configure SyncFlaer to use Kubernetes Ingresses.

**Comment by begna112** [comment]
okay I'm trying, but doesn't seem to work. 

docker-compose:
```
  syncflaer:
    container_name: syncflaer
    image: ghcr.io/containeroo/syncflaer:latest
    environment:
      - PUID=${PUID}
      - GUID=${PGID}
      - TZ=$TZ
      - CF_API_TOKEN=$CLOUDFLARE_TOKEN
      - TRAEFIK_PW=$TRAEFIK_PW
      - KUBECONFIG=/kube/config
    restart: unless-stopped
    volumes:
      - "${DOCKER_APPDATA}/syncflaer/config.yml:/config.yml"
```

/kube/config:
```
wiki.example.com/proxied="false"
wikidb.example.com/proxied="false"
```

no changes at all in cloudflare and not seeing anything in logs with `docker logs --follow --tail 50 syncflaer | grep wiki`
