### ISSUE TITLE
Feature Request: Ignore certain manually set records

### ISSUE THREAD

**Issue by stephanrenggli** [containeroo/SyncFlaer#158]
I would like to request a feature to exclude certain (manually created) DNS records from being managed (deleted) by SyncFlaer.

## Use Case
I am using a domain for services proxied by traefik. SyncFlaerautomatically manages those records and the root record.
I have now started using the same domain for ProtonMail. ProtonMail requires certain CNAME records to be set on the domain.

## Proposed Solution
I could set these records using SyncFlaer but I would prefer to be able to specify that SyncFlaer ignores certain records (ideally following a regex pattern). That way I could tell SyncFlaer to ignore (and therefor not delete) all records containing `protonmail`.

In the config this could be similar to additionalRecords.
I have also tried just setting the required CNAME records using SyncFlaer additionalRecords, however for some reason those records are continuously updated for no apparent reason.

**Comment by rxbn** [comment]
Hi @stephanrenggli 

Thanks for opening an issue! Before we proceed, I would like to know what exactly happened to the CNAME records. Could you please provide me with an example additionalRecord? What do you mean with "continuously updated for no apparent reason"?

Many thanks,
-- Robin

**Comment by stephanrenggli** [comment]
I created the following additionalRecords in `config.yml`:

```
additionalRecords:
  # ProtonMail example.com
  - name: protonmail._domainkey.example.com
    type: CNAME
    content: protonmail.domainkey.<random string>.domains.proton.ch.
  - name: protonmail2._domainkey.example.com
    type: CNAME
    content: protonmail2.domainkey.<random string>.domains.proton.ch.
  - name: protonmail3._domainkey.example.com
    type: CNAME
    content: protonmail3.domainkey.<random string>.domains.proton.ch.
```

These records are provided by ProtonMail in the domain setup process. Once added the container logs showed the records were being continuously updated. Example logs below:

```
time="2023-01-01T01:44:45Z" level=info msg="Updated: name: protonmail2._domainkey.example.com, type: CNAME, content: protonmail2.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 1"
time="2023-01-01T01:44:47Z" level=info msg="Updated: name: protonmail3._domainkey.example.com, type: CNAME, content: protonmail3.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 1"
time="2023-01-01T01:44:49Z" level=info msg="Updated: name: protonmail._domainkey.example.com, type: CNAME, content: protonmail.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 1"
time="2023-01-01T01:44:56Z" level=info msg="Updated: name: protonmail2._domainkey.example.com, type: CNAME, content: protonmail2.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 1"
time="2023-01-01T01:44:58Z" level=info msg="Updated: name: protonmail3._domainkey.example.com, type: CNAME, content: protonmail3.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 1"
time="2023-01-01T01:44:59Z" level=info msg="Updated: name: protonmail._domainkey.example.com, type: CNAME, content: protonmail.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 1"
time="2023-01-01T01:45:10Z" level=info msg="Updated: name: protonmail2._domainkey.example.com, type: CNAME, content: protonmail2.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 1"
time="2023-01-01T01:45:11Z" level=info msg="Updated: name: protonmail3._domainkey.example.com, type: CNAME, content: protonmail3.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 1"
time="2023-01-01T01:45:13Z" level=info msg="Updated: name: protonmail._domainkey.example.com, type: CNAME, content: protonmail.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 1"
```

As you can see, the records seem to be updated every few seconds. Between the updates, nothing was changed, so the record wouldn't need updating from what I can see. The records are created correctly on CloudFlare.

I do have another additionalRecord which works fine. So maybe the issue is related to the `content` field?

```
additionalRecords:
  - name: test.example.com
    type: CNAME
```

The `cloudflare:` section in `config.yml` contains the following:

```
cloudflare:
  apiToken: <token>
  zoneNames:
    - example.com
  deleteGrace: 10
  defaults:
    type: CNAME
    proxied: false
    ttl: 1
```

Let me know if you need additional details.

**Comment by rxbn** [comment]
Thanks! Could you please try the following additionalRecord configuration:

```yaml
additionalRecords:
  # ProtonMail example.com
  - name: protonmail._domainkey.example.com
    type: CNAME
    content: protonmail.domainkey.<random string>.domains.proton.ch.
    ttl: 120
  - name: protonmail2._domainkey.example.com
    type: CNAME
    content: protonmail2.domainkey.<random string>.domains.proton.ch.
    ttl: 120
  - name: protonmail3._domainkey.example.com
    type: CNAME
    content: protonmail3.domainkey.<random string>.domains.proton.ch.
    ttl: 120
```

I have added the `ttl: 120` config. It might be required due to Cloudflare API limitations.

**Comment by stephanrenggli** [comment]
Thanks for the quick reply!

I tried your exact configuration, however this didn't seem to fix the issue:

```
time="2023-01-01T19:10:09Z" level=info msg="Created: name: protonmail._domainkey.example.com, type: CNAME, content: protonmail.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 120"
time="2023-01-01T19:10:10Z" level=info msg="Created: name: protonmail2._domainkey.example.com, type: CNAME, content: protonmail2.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 120"
time="2023-01-01T19:10:11Z" level=info msg="Created: name: protonmail3._domainkey.example.com, type: CNAME, content: protonmail3.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 120"

time="2023-01-01T19:10:21Z" level=info msg="Updated: name: protonmail2._domainkey.example.com, type: CNAME, content: protonmail2.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 120"
time="2023-01-01T19:10:24Z" level=info msg="Updated: name: protonmail3._domainkey.example.com, type: CNAME, content: protonmail3.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 120"
time="2023-01-01T19:10:27Z" level=info msg="Updated: name: protonmail._domainkey.example.com, type: CNAME, content: protonmail.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 120"
time="2023-01-01T19:10:34Z" level=info msg="Updated: name: protonmail2._domainkey.example.com, type: CNAME, content: protonmail2.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 120"
time="2023-01-01T19:10:36Z" level=info msg="Updated: name: protonmail3._domainkey.example.com, type: CNAME, content: protonmail3.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 120"
time="2023-01-01T19:10:38Z" level=info msg="Updated: name: protonmail._domainkey.example.com, type: CNAME, content: protonmail.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 120"
time="2023-01-01T19:10:46Z" level=info msg="Updated: name: protonmail2._domainkey.example.com, type: CNAME, content: protonmail2.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 120"
time="2023-01-01T19:10:48Z" level=info msg="Updated: name: protonmail3._domainkey.example.com, type: CNAME, content: protonmail3.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 120"
time="2023-01-01T19:10:50Z" level=info msg="Updated: name: protonmail._domainkey.example.com, type: CNAME, content: protonmail.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 120"
time="2023-01-01T19:10:57Z" level=info msg="Updated: name: protonmail2._domainkey.example.com, type: CNAME, content: protonmail2.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 120"
time="2023-01-01T19:10:59Z" level=info msg="Updated: name: protonmail3._domainkey.example.com, type: CNAME, content: protonmail3.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 120"
time="2023-01-01T19:11:01Z" level=info msg="Updated: name: protonmail._domainkey.example.com, type: CNAME, content: protonmail.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 120"
time="2023-01-01T19:11:07Z" level=info msg="Updated: name: protonmail2._domainkey.example.com, type: CNAME, content: protonmail2.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 120"
time="2023-01-01T19:11:09Z" level=info msg="Updated: name: protonmail3._domainkey.example.com, type: CNAME, content: protonmail3.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 120"
time="2023-01-01T19:11:11Z" level=info msg="Updated: name: protonmail._domainkey.example.com, type: CNAME, content: protonmail.domainkey.<random string>.domains.proton.ch., proxied: false, ttl: 120"

time="2023-01-01T19:11:28Z" level=info msg="Waiting 9 more runs until DNS record protonmail2._domainkey.example.com gets deleted"
time="2023-01-01T19:11:29Z" level=info msg="Waiting 9 more runs until DNS record protonmail3._domainkey.example.com gets deleted"
time="2023-01-01T19:11:30Z" level=info msg="Waiting 9 more runs until DNS record protonmail._domainkey.example.com gets deleted"
```

The first 3 messages show the records being created, the next few are the mentioned updates (no configuration changes occurred, the <random string> is always the same as well). I then commented out the records in `config.yml`, so they get marked for deletion in the last 3 messages.

CloudFlare screenshot of the created records:

![image](https://user-images.githubusercontent.com/5135902/210182220-053545fe-c1b3-45d6-a99c-cf481364583c.png)

**Comment by rxbn** [comment]
Hmm... this must me some kind of weird bug. I'm digging into it!

**Comment by rxbn** [comment]
I found the issue! It looks like either SyncFlaer or Cloudflare API don't like the trailing `.`.

Could you please try it again with the following config:


```yaml
additionalRecords:
  # ProtonMail example.com
  - name: protonmail._domainkey.example.com
    type: CNAME
    content: protonmail.domainkey.<random string>.domains.proton.ch # here I removed the dot
  - name: protonmail2._domainkey.example.com
    type: CNAME
    content: protonmail2.domainkey.<random string>.domains.proton.ch # here I removed the dot
  - name: protonmail3._domainkey.example.com
    type: CNAME
    content: protonmail3.domainkey.<random string>.domains.proton.ch  # here I removed the dot
```

Also make sure you use the latest version of SyncFlaer.
