### ISSUE TITLE
Add support for multiple Traefik instances

### ISSUE THREAD

**Issue by ielio** [containeroo/SyncFlaer#20]
# Add support for multiple Traefik instances
The new YAML config could look like this?
```YAML
traefik:
  # add multiple instances
  <TRAEFIK_1>:
    url: https://traefik_1.example.com
    username: admin1
    password: supersecure1  # can also be set using <TRAEFIK_1>_PASSWORD env variable
  <TRAEFIK_2>:
    url: https://traefik_2.example.com
    username: admin2
    password: supersecure2  # can also be set using <TRAEFIK_2>_PASSWORD env variable

```

## Suggestion:
Add a `map` type of Traefiks
```Go
// Traefiks holds the Traefik list.
type Traefiks map[string]*Traefik
```
See [docs](https://blog.golang.org/maps)
Then we can declare as many Traefik instances as we wish.

Thank you for your feedback!
