### ISSUE TITLE
[Feature] Add cloudflared (argo) tunnel DNS discovery

### ISSUE THREAD

**Issue by rockaut** [containeroo/SyncFlaer#39]
#### Summary

It would be so nice to also have this included.
In newer releases cloudflared is configured mostly through config files which contains the routes (`ingress:`).
In older releases the given Domains where automagically added to CF DNS. Sadly this isn't the case anymore.

#### How?

So a way to implement this could be:
- get the created tunnels through the API
- read the config-files (possibility of multiple files/paths)
- check if DNS present according to config and tunnel
- maybe even remove DNS if not present in config but still in CF DNS

minimal config.yml example:

```yaml
tunnel: example

ingress:
  - hostname: example.domain.net
    service: http://10.0.0.1:81
  - service: http_status:404
``

I the path with the config also has to be a "key" file for cloudflared with the tunnel-id as filename:

a-b-c.json
```json
{"AccountTag":"x-y-z","TunnelSecret":"somerandomsecret","TunnelID":"a-b-c","TunnelName":"example"}
```

#### Usecase

My usecase here is basically this: I don't expose my traefik endpoints/routes to the public but instead have an internal DNS resolving those DNS ... internally. Additionally an cloudflared is configured to also have these urls in ingress and the public CF DNS is tunneling public requests through cloudflared into traefik.

```ASCII
internal Request --> internal DNS -+
                                   |
                                   +-> Traefik --> Service
                                   |
external Request --> CF DNS -------+
```
